### ISSUE TITLE
[Enhancement] func parse_custodian_results 

### ISSUE THREAD

**Issue by saurabh3460** [runwhen-contrib/aws-c7n-codecollection#7]
Rename this function to a more generic name. However, there is already a function named `parse_custodian_results`. To avoid confusion, update `parse_custodian_results` function to better match its purpose of handling S3, EBS, and EC2 (for now) `resource` and `metadata`.

https://github.com/runwhen-contrib/aws-c7n-codecollection/blob/71e904600a0a3ae991f505636a0b147c2c3a8e56/libraries/CloudCustodian/Core/Core.py#L171

cc @stewartshea

**Comment by stewartshea** [comment]
@saurabh3460 I'm not exactly clear what is being asked of here, please propose your change in a Pull Request and test the CodeBundles this change affects.

**Comment by saurabh3460** [comment]
Ok, Will create a PR once EC2 codebundle is merge, because in EC2 codebundle I am using func `parse_ebs_results` where I have made changes to support ec2 resource's cloudcustodian output
